l=[]
for i in range(9):
    num=int(input("enter elements"))
    l.append(num)
print(l)
pos=int(input("enter pos"))
posi=l.pop(pos)
print(l)
rem=int(input("enter elements presnt in list to delete"))
remo=l.remove(rem)
print(l)
inser=int(input("enter the element to insert"))
inse=int(input("enter value"))
ins=l.insert(inser,inse)
print(l)
ind=int(input("enter the position"))
index=l.index(ind)
print(index)
po=int(input("enter index to remove"))
poo=l.pop(po)
print(l)
